name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install 7zip
        run: sudo apt-get install p7zip-full

      - name: Create bundle
        run: 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on bundle.7z .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bundle.7z
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.release.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
